export { default as AddPlaylist } from "./addPlaylist/AddPlaylist";
export { default as NavBar } from "./navBar/NavBar";
export { default as Player } from "./player/Player";
export { default as SongList } from "./songList/SongList";
export { default as AddMusic } from "./addMusic/AddMusic";
export { default as DeleteMusic } from "./deleteMusic/DeleteMusic";
export { default as SetRight } from "./setRight/SetRight";
export { default as UserHistory } from "./userHistory/UserHistory";
export { default as UserPlaylist } from "./userPlaylist/UserPlaylist";
